# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank='False', max_length=10)),
                ('phone', models.IntegerField(blank='False')),
                ('home_addr', models.CharField(blank='False', max_length=40)),
                ('work_addr', models.CharField(blank='False', max_length=40)),
                ('profession', models.CharField(blank='False', max_length=15)),
                ('company', models.CharField(blank='False', max_length=16)),
                ('is_married', models.NullBooleanField()),
                ('photo', models.ImageField(upload_to='photo')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
