# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='班级名')),
                ('student_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='people',
            name='is_monitor',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='people',
            name='company',
            field=models.CharField(blank='False', max_length=16, verbose_name='公司/职位'),
        ),
        migrations.AlterField(
            model_name='people',
            name='home_addr',
            field=models.CharField(blank='False', max_length=40, verbose_name='家庭住址'),
        ),
        migrations.AlterField(
            model_name='people',
            name='is_married',
            field=models.NullBooleanField(verbose_name='婚否 '),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(blank='False', max_length=10, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='people',
            name='phone',
            field=models.IntegerField(blank='False', verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='people',
            name='photo',
            field=models.ImageField(upload_to='photo', verbose_name='近期照片'),
        ),
        migrations.AlterField(
            model_name='people',
            name='profession',
            field=models.CharField(blank='False', max_length=15, verbose_name='从事行业'),
        ),
        migrations.AlterField(
            model_name='people',
            name='work_addr',
            field=models.CharField(blank='False', max_length=40, verbose_name='工作地址'),
        ),
        migrations.AddField(
            model_name='people',
            name='myclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.MyClass'),
        ),
    ]
