# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20160728_0237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myclass',
            options={'verbose_name': '班级', 'verbose_name_plural': '班级'},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name': '同学', 'verbose_name_plural': '同学'},
        ),
        migrations.AlterField(
            model_name='people',
            name='is_monitor',
            field=models.BooleanField(default=0, verbose_name='班长'),
        ),
        migrations.AlterField(
            model_name='people',
            name='myclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.MyClass', verbose_name='所属班级'),
        ),
    ]
