# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20160720_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myclass',
            name='student_number',
        ),
        migrations.AddField(
            model_name='myclass',
            name='password',
            field=models.CharField(blank='False', max_length=30, verbose_name='暗号'),
        ),
    ]
